# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Research
# email: your-email@example.com
description: Research material & information about topics I find interesting.
show_downloads: false
domain: research.zendai.net.eu.org
url: https://research.zendai.net.eu.org
# baseurl: "" # the subpath of your site, e.g. /blog

nav:
  - title: "ARC - A Responsible Citizenry"
    url: "{{ site.url }}/page/arc.html"
  - title: Code
    url: "{{ site.url }}/page/code.html"
    subnav:
      - title: Bash
        url: "{{ site.url }}/page/code/bash.html"
        subnav:
          - title: "Bash functions"
            url: "{{ site.url }}/page/code/bash/functions.html"
      - title: Caddy
        url: "{{ site.url }}/page/code/caddy.html"
      - title: Git
        url: "{{ site.url }}/page/code/git.html"
      - title: Python
        url: "{{ site.url }}/page/code/python.html"
  - title: Notes
    url: "{{ site.url }}/page/notes.html"

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight

# # Some configuration settings cannot be changed for GitHub Pages sites.
# lsi: false
# safe: true
# #source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge

#github: [metadata]

# GitHub Pages uses plugins that are enabled by default and cannot be disabled:
# 
#     jekyll-coffeescript
#     jekyll-default-layout
#     jekyll-gist
#     jekyll-github-metadata
#     jekyll-optional-front-matter
#     jekyll-paginate
#     jekyll-readme-index
#     jekyll-titles-from-headings
#     jekyll-relative-links
