[package]
name = "toolbox"
version = "0.1.0"
edition = "2021"
authors = ["Victor-ray, S."]
publish = false

# description = ""
# documentation = ""
# readme = ""
# homepage = ""
# repository = ""
# license = ""
# license-file = ""
# keywords = [""]
# categories = [""]
# workspace = ""
# build = ""
# exclude = [""]
# include = [""]
# publish = [""]
# [profile.dev]
# opt-level = 0
# [profile.release]
# opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
# walkdir = "2"
# zen = { path = "../zen" }
