version: "3.7"
volumes:
  nextcloud:
  db:
  caddy_data: {}

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:fpm
    restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - APACHE_DISABLE_REWRITE_IP=1
      #- OVERWRITEPROTOCOL=http
      #- TRUSTED_PROXIES=192.168.178.12
      #- TRUSTED_PROXIES=172.22.0.1
      #- TRUSTED_PROXIES=127.0.0.1
      #- APACHE_IP_BINDING=127.0.0.1

  web:
    # see here for guidance on which image / tag to choose:
    # https://github.com/lucaslorentz/caddy-docker-proxy#docker-images
    image: caddy
    ports:
      #- 80:80
      #- 443:443
      - 8080:80
      - 8443:8443
    links:
      - app
#    environment:
#      - CADDY_INGRESS_NETWORKS=caddy
#    networks:
#      caddy:
#        ipv4_address: 172.16.0.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    volumes_from:
      - app
    restart: always

#networks:
#  caddy:
#    external: true

